updates `cp` to keep the previous behavour
my new implementation of the `cp` function got merged
https://github.com/JuliaLang/julia/pull/10888

sets `remove_destination=true` otherwise if you rerun you get an:

```
ERROR: ArgumentError: 'static/custom.css' exists.
`remove_destination=true` is required to remove
'static/custom.css' before copying.
```